sudo: required
language: node_js
node_js:
  - "8.11.1"

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls: https://webhooks.gitter.im/e/627a6148acaaeddc21b9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_script:
  - npm install
script:
  - npm run test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./test/unit/coverage/lcov.info
  - npm run build
  - export DOCKER_TAG=$TRAVIS_BRANCH-$TRAVIS_COMMIT
  - docker build -t hkustvislab/vismooc-front-end:elearning-$TRAVIS_BRANCH -t hkustvislab/vismooc-front-end:elearning-$DOCKER_TAG .
  - docker login -u="$DOCKER_EMAIL" -p="$DOCKER_PASSWORD"
  - docker push hkustvislab/vismooc-front-end
