export const GET_COURSES_LIST = 'GET_COURSES_LIST';
export const SELECT_COURSE = 'SELECT_COURSE';
export const SELECT_VIDEO = 'SELECT_VIDEO';
export const FETCH_CLICKS = 'FETCH_CLICKS';
export const FETCH_DEMOGRAPHICINFO = 'FETCH_DEMOGRAPHICINFO';
export const UPDATE_CLICKS_FILTER = 'UPDATE_CLICKS_FILTER';
// Sentiment
export const FETCH_SENTIMENT = 'FETCH_SENTIMENT';
// SocialNetwork
export const FETCH_FORUMSOCIALNETWORK = 'FETCH_FORUMSOCIALNETWORK';
export const FETCH_WORDCLOUD = 'FETCH_WORDCLOUD';

export const LOADING = 'LOADING';
export const FINISHED_LOADING = 'FINISHED_LOADING';
export const LOGINED = 'LOGINED';
export const LOGOUTED = 'LOGOUTED';

export default {
    GET_COURSES_LIST,
    SELECT_COURSE,
    SELECT_VIDEO,
    FETCH_CLICKS,
    FETCH_DEMOGRAPHICINFO,
    UPDATE_CLICKS_FILTER,

    FETCH_SENTIMENT,
    FETCH_FORUMSOCIALNETWORK,
    FETCH_WORDCLOUD,

    LOADING,
    FINISHED_LOADING,
    LOGINED,
    LOGOUTED,
};
